name: Vercel Deploy
on:
    push:
        branches: [master]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Install frontend dependencies
              run: npm install
              working-directory: ./frontend
            - name: Build frontend
              run: npm run build
              working-directory: ./frontend
            - name: Vercel Action
              uses: amondnet/vercel-action@v20
              with:
                vercel-token: ${{ secrets.VERCEL_TOKEN }}
                vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}